# GET http://localhost:3000/api/products/category/organic

# POST  http://localhost:3000/api/products
# Content-Type: application/json

# {
#     "category": 3242,
#     "title": "White Bread - Freshly Baked by Origin Bakery",
#     "price": 99,
#     "favorite": false,
#     "img": 23432,
#     "netWeight": 100,
#     "stock": 3
# }


# DELETE http://localhost:3000/api/products/6889b47095ecc722f461497ee


# GET http://localhost:3000/api/news?take=2&order=asc

# POST  http://localhost:3000/api/news
# Content-Type: application/json

# {
#     "category": "Health",
#     "title": "New Health Guidelines Released",
#     "date": "2023-10-01",
#     "comments": "This is a comment",
#     "img": "https://example.com/image.jpg",
#     "description": "A detailed description of the health guidelines."
# }

# DELETE http://localhost:3000/api/news/688af8114efb2970ebf2f353

# POST http://localhost:3000/api/users 
# Content-Type: application/json

# {
#     "name": "ilham",
#     "username": "ilham123",
#     "email": "asususer3039@outlook.com",
#     "password": "ilham123"
# }

# POST http://localhost:3000/api/auth/login
# Content-Type: application/json

# {
#     "email": "asususer3039@outlook.com",
#     "password": "123"
# }


# POST http://localhost:3000/api/auth/login
# Content-Type: application/json

# {
#     "email"
# }

# GET http://localhost:3000/api/auth/session
# Cookie: session=ENCRYPTED_DATA.HMAC_SIGNATURE